// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1Sv6O2qN29PJobkUMEQDQGqSW86gBbWo',
    appId: '1:327181082964:web:690e58b0ea1e2dfce5a8c1',
    messagingSenderId: '327181082964',
    projectId: 'rural-8c3b7',
    authDomain: 'rural-8c3b7.firebaseapp.com',
    databaseURL: 'https://rural-8c3b7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rural-8c3b7.firebasestorage.app',
    measurementId: 'G-Y8JLGJSTHM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAW5OWnrOd0mhEFPaW1kBsYqW8p5cdkE1M',
    appId: '1:327181082964:android:4c200ee2996a3e80e5a8c1',
    messagingSenderId: '327181082964',
    projectId: 'rural-8c3b7',
    databaseURL: 'https://rural-8c3b7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rural-8c3b7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbLnGEzhOC503f3ezqMUTKkPeK_4M9fJY',
    appId: '1:327181082964:ios:0242d112e7afab48e5a8c1',
    messagingSenderId: '327181082964',
    projectId: 'rural-8c3b7',
    databaseURL: 'https://rural-8c3b7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rural-8c3b7.firebasestorage.app',
    iosClientId: '327181082964-oiargst6btfpclqdss8qf10mtsosddmo.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbLnGEzhOC503f3ezqMUTKkPeK_4M9fJY',
    appId: '1:327181082964:ios:0242d112e7afab48e5a8c1',
    messagingSenderId: '327181082964',
    projectId: 'rural-8c3b7',
    databaseURL: 'https://rural-8c3b7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rural-8c3b7.firebasestorage.app',
    iosClientId: '327181082964-oiargst6btfpclqdss8qf10mtsosddmo.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCR53B0X40XX_TfURCWvJmKDbFaU4zFdwU',
    appId: '1:327181082964:web:6f715a54694c5405e5a8c1',
    messagingSenderId: '327181082964',
    projectId: 'rural-8c3b7',
    authDomain: 'rural-8c3b7.firebaseapp.com',
    databaseURL: 'https://rural-8c3b7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rural-8c3b7.firebasestorage.app',
    measurementId: 'G-0EQLG3BFME',
  );
}
